[
  {
    postData: {
      title: "A Great Apartment in Andheri West",
      images: [
        "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg",
      ],
      bedroom: 2,
      bathroom: 1,
      price: 23000,
      address: "Andheri West, Mumbai",
      latitude: "19.1350",
      longitude: "72.8611",
      type: "rent",
      property: "apartment",
      city: "Mumbai",
    },
    postDetail: {
      utilities: "owner",
      income: "3x",
      size: 88,
      school: 250,
      bus: 100,
      restaurant: 50,
      desc: "Modern flat with easy access to metro, schools and cafes. Ideal for young professionals or small families.",
    },
  },
  {
    postData: {
      title: "Spacious House in BTM Layout",
      images: [
        "https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg",
      ],
      bedroom: 3,
      bathroom: 2,
      price: 35000,
      address: "BTM Layout 2nd Stage, Bengaluru",
      latitude: "12.9141",
      longitude: "77.6101",
      type: "rent",
      property: "house",
      city: "Bangalore",
    },
    postDetail: {
      utilities: "tenant",
      income: "2.5x",
      size: 120,
      school: 300,
      bus: 50,
      restaurant: 100,
      desc: "Peaceful house in a tech hub. Suitable for remote workers and families.",
    },
  },
  {
    postData: {
      title: "Affordable Flat near Salt Lake Sector V",
      images: [
        "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg",
      ],
      bedroom: 1,
      bathroom: 1,
      price: 12000,
      address: "Sector V, Salt Lake City, Kolkata",
      latitude: "22.5850",
      longitude: "88.4170",
      type: "rent",
      property: "apartment",
      city: "Kolkata",
    },
    postDetail: {
      utilities: "owner",
      income: "2x",
      size: 65,
      school: 180,
      bus: 70,
      restaurant: 60,
      desc: "Single-bedroom flat for bachelors or students. All amenities nearby.",
    },
  },
  {
    postData: {
      title: "Luxury Condo in Jubilee Hills",
      images: [
        "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg",
      ],
      bedroom: 3,
      bathroom: 2,
      price: 45000,
      address: "Jubilee Hills, Hyderabad",
      latitude: "17.4270",
      longitude: "78.4128",
      type: "rent",
      property: "condo",
      city: "Hyderabad",
    },
    postDetail: {
      utilities: "tenant",
      income: "4x",
      size: 145,
      school: 320,
      bus: 60,
      restaurant: 40,
      desc: "Beautiful view of the city skyline, 24x7 security and gym included.",
    },
  },
  {
    postData: {
      title: "Budget Room near Charbagh Station",
      images: [
        "https://images.pexels.com/photos/261146/pexels-photo-261146.jpeg",
      ],
      bedroom: 1,
      bathroom: 1,
      price: 7500,
      address: "Charbagh, Lucknow",
      latitude: "26.8358",
      longitude: "80.9462",
      type: "rent",
      property: "apartment",
      city: "Lucknow",
    },
    postDetail: {
      utilities: "owner",
      income: "1.5x",
      size: 45,
      school: 200,
      bus: 30,
      restaurant: 20,
      desc: "Basic room for working individuals, railway station in walking distance.",
    },
  },
  {
    postData: {
      title: "2BHK Flat near MG Road",
      images: [
        "https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg",
      ],
      bedroom: 2,
      bathroom: 2,
      price: 28000,
      address: "MG Road, Pune",
      latitude: "18.5204",
      longitude: "73.8567",
      type: "rent",
      property: "apartment",
      city: "Pune",
    },
    postDetail: {
      utilities: "tenant",
      income: "3x",
      size: 90,
      school: 200,
      bus: 100,
      restaurant: 80,
      desc: "Spacious flat near major IT parks, metro connectivity and markets.",
    },
  },
  {
    postData: {
      title: "Modern Studio in Civil Lines",
      images: [
        "https://images.pexels.com/photos/221540/pexels-photo-221540.jpeg",
      ],
      bedroom: 1,
      bathroom: 1,
      price: 18000,
      address: "Civil Lines, Jaipur",
      latitude: "26.9124",
      longitude: "75.7873",
      type: "rent",
      property: "apartment",
      city: "Jaipur",
    },
    postDetail: {
      utilities: "owner",
      income: "2x",
      size: 55,
      school: 180,
      bus: 90,
      restaurant: 65,
      desc: "Designer studio in posh locality. Great for young couples or professionals.",
    },
  },
  {
    postData: {
      title: "Spacious Family Home in Anna Nagar",
      images: [
        "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg",
      ],
      bedroom: 4,
      bathroom: 3,
      price: 38000,
      address: "Anna Nagar, Chennai",
      latitude: "13.0827",
      longitude: "80.2707",
      type: "rent",
      property: "house",
      city: "Chennai",
    },
    postDetail: {
      utilities: "tenant",
      income: "3x",
      size: 160,
      school: 350,
      bus: 100,
      restaurant: 120,
      desc: "Big independent house with garden, parking and gated community access.",
    },
  },
  {
    postData: {
      title: "2BHK Near Sector 62 Metro",
      images: [
        "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg",
      ],
      bedroom: 2,
      bathroom: 2,
      price: 20000,
      address: "Sector 62, Noida",
      latitude: "28.6139",
      longitude: "77.2090",
      type: "rent",
      property: "apartment",
      city: "Noida",
    },
    postDetail: {
      utilities: "owner",
      income: "2.5x",
      size: 85,
      school: 300,
      bus: 80,
      restaurant: 90,
      desc: "Freshly renovated flat in a quiet society. Metro and markets nearby.",
    },
  },
  {
    postData: {
      title: "1RK in Sector 22, Chandigarh",
      images: [
        "https://images.pexels.com/photos/221540/pexels-photo-221540.jpeg",
      ],
      bedroom: 1,
      bathroom: 1,
      price: 10000,
      address: "Sector 22, Chandigarh",
      latitude: "30.7333",
      longitude: "76.7794",
      type: "rent",
      property: "apartment",
      city: "Chandigarh",
    },
    postDetail: {
      utilities: "tenant",
      income: "2x",
      size: 40,
      school: 150,
      bus: 50,
      restaurant: 30,
      desc: "Studio room for students or singles. Clean locality with food joints.",
    },
  },
];
